before:
  hooks:
    - go mod download
builds:
  - skip: true
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
    - "ghcr.io/humweb/inertia-go:latest"
    - "ghcr.io/humweb/inertia-go:{{ .Major }}"
    - "ghcr.io/humweb/inertia-go:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/humweb/inertia-go:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
  disable: true
changelog:
  skip: true
